name = "acmoi"
defaultTargets = ["Acmoi"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "Acmoi"
